// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5et_5TOEew77YX9hV-XoayPIrAfT5vEg',
    appId: '1:286303873419:web:65d20b3da21d9bea8a278e',
    messagingSenderId: '286303873419',
    projectId: 'trab-persistencia',
    authDomain: 'trab-persistencia.firebaseapp.com',
    storageBucket: 'trab-persistencia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiJyx6UeNbfMWPTG7E9y0mL78Ok-oPus',
    appId: '1:286303873419:android:5f531b9a204b0dd78a278e',
    messagingSenderId: '286303873419',
    projectId: 'trab-persistencia',
    storageBucket: 'trab-persistencia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5qEqoaYfutHFaA2CMPSxyBi8-wNsWzAA',
    appId: '1:286303873419:ios:6ffce0c3c1f8a4bb8a278e',
    messagingSenderId: '286303873419',
    projectId: 'trab-persistencia',
    storageBucket: 'trab-persistencia.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5qEqoaYfutHFaA2CMPSxyBi8-wNsWzAA',
    appId: '1:286303873419:ios:6ffce0c3c1f8a4bb8a278e',
    messagingSenderId: '286303873419',
    projectId: 'trab-persistencia',
    storageBucket: 'trab-persistencia.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5et_5TOEew77YX9hV-XoayPIrAfT5vEg',
    appId: '1:286303873419:web:a309327ba48d5c728a278e',
    messagingSenderId: '286303873419',
    projectId: 'trab-persistencia',
    authDomain: 'trab-persistencia.firebaseapp.com',
    storageBucket: 'trab-persistencia.firebasestorage.app',
  );
}
